### ISSUE TITLE
Make vscode-xslt available in Extension Marketplace

### ISSUE THREAD

**Issue by riberon** [szul/vscode-xslt#1]
I would like to use this extension but could not find it in the extension market place. Do you plan to make it available by searching for extensions directly in VS Code?

**Comment by brendanheyu** [comment]
I too am looking for some XSL magic in VS Code....
What are my chances? I'm currently have to render my transforms in Dreamweaver - have pity!!! :)

**Comment by szul** [comment]
@brendanheyu I originally did a PR to the XMLTools extension, but the repo owner let that sit and then a bot closed it for being stale. I'll find some time to revisit this this week, and get an MVP in the extension marketplace.

**Comment by szul** [comment]
@riberon Just now seeing your comment. Not sure how it slipped by me. See my comment above.

**Comment by szul** [comment]
Resolved by commit 81df80191b61acff731e700c3902d5f4155621d6
